### ISSUE TITLE
Handling push notification in Flutter code

### ISSUE THREAD

**Issue by wal33d006** [customerio/customerio-flutter#103]
I have been trying to somehow read & trigger some of my own code inside Flutter as soon as the notification is received/clicked but I can't find any function or any documentation that tells me exactly how to do it. Am I missing something? Can somebody help with this? It might be a very naive thing or maybe it's meant that way, any explanation would help.
Cheers!

**Comment by Shahroz16** [comment]
Hey @wal33d006, thank you for writing in. There is currently no callback for when a notification is `received/clicked`.

**Comment by Shahroz16** [comment]
Hey @wal33d006, it's not currently possible. It's in our roadmap but not possible at the moment.
