### ISSUE TITLE
Feature Request: Custom Routing based on links from push message

### ISSUE THREAD

**Issue by jonalecpalustre** [customerio/customerio-flutter#104]
FR: User would like be able to do custom routing by grabbing the link/URL from the push when it's clicked.

https://customer7760.zendesk.com/agent/tickets/75754
ACCT: 
  Braive As
 (Account #34123 [Basic] | Datacenter: eu) | 

Currently, they have a workaround by setting up a route guard that prevents the routing to happen and then intercepting the link with a third party framework. 

**USE CASE:**

> The biggest challenge we have is that we always want to do some custom routing based on the link. We are using GetX and the default behavior is that it immediately tries to route to the link when the push is clicked. But we first need to make sure the user is logged in and then we sometimes just want the tab in the tabbar to be changed and sometimes we want to push several screens.

**Comment by ami-aman** [comment]
Closing this as this ticket has been added to Mobile Squad's internal board.
