### ISSUE TITLE
Gradle 8 support

### ISSUE THREAD

**Issue by gohar-ali-coingaming** [customerio/customerio-flutter#107]
hi!

I am trying to implement customer.io flutter sdk and found this issue regarding name space.  

-----------
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@1cd91fd7 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':customer_io'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

           If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

Fix is fairly simple, adding name space in the build.gradle should help.
https://developer.android.com/build/configure-app-module#set-namespace

**Comment by gohar-ali-coingaming** [comment]
thanks @halbano,
- Downgrade Gradle to a 7.x version is not an option for us, as we have spent a lot time upgrading it and we put effort to keep our project as updated as possible.
- I am gonna use the override subprojects namespace, however, customer-io is the only project with this issue. And would be great if we can avoid this kind of patches from our code. 

Looking forward to updated SDK with latest gradle version support soon 💪

**Comment by AristideVB** [comment]
Any updates on this issue ?

**Comment by Korefey** [comment]
@levibostian 
When is support for version 8 planned?

**Comment by Shahroz16** [comment]
Hey @Korefey, thank you for reaching out. Happy to inform it's part of current development cycle and while I can't give any timeline, I assure you it's been worked and we plan to roll out Gradle 8 support as well R8 full mode support that is enabled by default in Gradle 8.

**Comment by mrehan27** [comment]
Happy to share that that the updates have been released in version [`1.4.0`](https://github.com/customerio/customerio-flutter/releases/tag/1.4.0), and the package is now fully compatible with Gradle 8. Please update to the latest version and let us know if you encounter any issues.
