### ISSUE TITLE
Add documentation for plugin

### ISSUE THREAD

**Issue by AristideVB** [customerio/customerio-flutter#11]
It would be nice, if this plugin had additional documentation, looks promising ! 🙂

**Comment by Shahroz16** [comment]
Hey @AristideVB, please check out the documentation [here](http://localhost:1313/docs/sdk/flutter/getting-started/).

**Comment by AristideVB** [comment]
Hi sorry but your link doesn't work @Shahroz16 🤕

**Comment by Shahroz16** [comment]
@AristideVB 🤦 updated it. Apologies.
