### ISSUE TITLE
Attributes not sent

### ISSUE THREAD

**Issue by Statyk7** [customerio/customerio-flutter#12]
Great to see this Flutter package for Customer.io! 

I understand this is still an early version but I wanted to give a try. I'm able to connect to my CIO instance, I'm getting activities (person created, event) with the right activity name but none of the attributes are sent apparently... Is it a current limitation or something I'm doing wrong?

I tried to debug in XCode, it seems the data map is not converted correctly when going through "StringAnyEncodable" when called from CustomerIOImplementation identify() or track()...

**Comment by Shahroz16** [comment]
Hey, @Statyk7 thank you for reporting this, the fix is being sent out right now, please check in the next update.
