### ISSUE TITLE
Build failed : invalid source release: 17 (JVM)

### ISSUE THREAD

**Issue by MickaelHrndz** [customerio/customerio-flutter#124]
I'm encountering this error when trying to build my app after upgrading Flutter:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':customer_io:compileReleaseJavaWithJavac'.
> error: invalid source release: 17
```

I suspect that it is caused by targeted jvm version specified in the build.gradle: 
https://github.com/customerio/customerio-flutter/blob/e6862c9a6b145d7264cfea95e7977c6f805eff52/android/build.gradle#L38

**Comment by Ahmed-Ali** [comment]
JVM 17 is requirement for Gradle 8.
Does the [answer here](https://stackoverflow.com/questions/69696321/intellij-invalid-source-release-17) helps?

**Comment by MickaelHrndz** [comment]
Ok my bad, I recently upgraded the whole project, and the build was successful locally but not on the CI pipeline. Turns out there's a **pipeline action to set the Java version**. I did and it solves the issue. I should've digged a little further before opening the issue, sorry for the inconvenience.
