### ISSUE TITLE
Set Push Token manually from Flutter

### ISSUE THREAD

**Issue by Statyk7** [customerio/customerio-flutter#13]
Instead of adding specific platform code to set the push token it would be convenient to expose a function to set it manually from Flutter. I was able to do it by calling the Tracking API with the Add Device endpoint: https://customer.io/docs/api/#operation/add_device

**Comment by Shahroz16** [comment]
Hey @Statyk7 thank you for reaching out, we have noted this down as a feature request, and will update on this soon.

**Comment by Jethro87** [comment]
@Statyk7 I'm curious if you integrated any/all of the platform specific code for push notifications. 

I've already set up FCM for my app, and am wondering if the platform code is necessary at all, or if I can simply handle push notifications as I'm already doing with the addition of sending notification tracking metrics and devices to customer.io. 

Any suggestions based on how you integrated would be welcome! Thanks.

**Comment by Shahroz16** [comment]
Hey @Statyk7, its been a long time coming but the latest [release: customer_io: ^1.0.0-alpha.8](https://pub.dev/packages/customer_io), you now have the ability to add a device, using this method.

```
 CustomerIO.registerDeviceToken(deviceToken: "device-token");
```

Closing this, please feel free to reach out, in case you have more questions.
