### ISSUE TITLE
ANR Issues with CustomerIO SDK

### ISSUE THREAD

**Issue by donpaul120** [customerio/customerio-flutter#147]
We are having a lot of production issues with the CustomerIO SDK

SDK : 1.4.0

<img width="1189" alt="Screenshot 2024-09-08 at 23 52 49" src="https://github.com/user-attachments/assets/42a405f9-72f0-4a86-a21e-f5001da0de4b">

**Comment by Shahroz16** [comment]
Hey @donpaul120 thank you for reaching out, apologies you are facing this issue. Are there any steps to reproduce here? or is it intermittent?

**Comment by donpaul120** [comment]
As with any thread issues they are quite hard to reproduce from our end, but having a glance at the code i think there seems to be problem with the way things are quite done on the main thread itself. 

We seem to be using a GlobalScope, a ticker from kotlin channels that's obsolete due to it's buggy nature. Apis to fetch userMessages are really not delegated to an IO dispatcher, i think all this can lead to us blocking the main thread.

I'd suggest we perhaps maintain a coroutineScope and use appropriate dispatchers where required.
e.g 
- perform the the "smart pooling" using separate dispatcher
- fetch messages using io dispatcher
- switch back to the main thread to display the in-app-message

These are a few things i was able to pick on at a glance, i could be wrong but i think issues with lock or blocks are not far from what GlobalScope delicate api can introduce.

We also seem to have this sort of spikes during campaigns. In general there are actually lot of issues we face from the customerIO sdk.

**Comment by Shahroz16** [comment]
@donpaul120 Thank you for the detailed response. What you have mentioned is already being done and can be found [here](https://github.com/customerio/customerio-android/pull/431). But I wanted to make sure that this does indeed resolve any of the ANRs you might be facing right now. 

Thank you for your patience as we test out these changes and then roll out to all platforms.

**Comment by donpaul120** [comment]
The changes looks good to me and could be a great improvement. Similar blocking problems occurs when initialising the WebView but i believe it is a subset of the main problem your fix covers. 

Thank you for your response.

**Comment by Shahroz16** [comment]
@donpaul120 update here, thank you for your patience. The changes are shipped in major Android SDK, we are currently discussing and working on what is the best path to bring these changes to flutter as these changes are coupled with some more changes and features like that of data pipelines. 

I'll keep you updated when we roll out the updates on flutter SDK.

**Comment by donpaul120** [comment]
@Shahroz16  Thank you very much! We are waiting on this.

**Comment by Shahroz16** [comment]
Awesome, thanks for your patience, will update here once done.

**Comment by donpaul120** [comment]
@Shahroz16 is there any update on this yet? We are really having a lot of issues on this.

**Comment by Shahroz16** [comment]
@donpaul120 apologies for the inconvenience you are facing here, but it's in the pipeline. Native SDKs have been updated, react native is going out next weeks and then we are going to focusing on Flutter. Change just doesn't bring the in-app updates but a lot new and exciting features like anonymous tracking etc.

**Comment by donpaul120** [comment]
@Shahroz16 Okay, thanks for the update! we'd be expecting this fixes.

**Comment by donpaul120** [comment]
@Shahroz16 Is there any update on this so far?

**Comment by Shahroz16** [comment]
@donpaul120 absolutely, react native is out and we are actively working on flutter now. Making good progress, thank you for your patience and I'll definitely reach out when we roll out the new release
