### ISSUE TITLE
Update Customer.io Flutter SDK to use iOS SDK 3.4.1

### ISSUE THREAD

**Issue by vendoshi** [customerio/customerio-flutter#151]
The current Customer.io Flutter SDK needs to be updated to support the latest iOS SDK version 3.4.1. This is help with supporting the latest Firebase SDK version.

https://github.com/customerio/customerio-ios/releases/tag/3.4.1

**Comment by scotttwittrockcio** [comment]
Hi @vendoshi the flutter SDK still relies on the 2.x version of our native iOS SDK. We are reviewing the feasibility of updating the 2.x iOS native SDK to support firebase 11 vs. the effort to complete the work to enable our Flutter SDK to utilize the 3.x version of our native iOS SDK. Once we review and decide on an approach we will have a better estimate on when this could be completed.

**Comment by vendoshi** [comment]
> @scotttwittrockcio I submitted a PR for the update for the 2.x version of the iOS SDK to support firebase newest version already [customerio/customerio-ios#824](https://github.com/customerio/customerio-ios/pull/824) - please go with this faster alternative

That sounds great. Could you please explain how to incorporate this into the Customer.io Flutter SDK?

**Comment by ami-aman** [comment]
We've released iOS SDK v[2.14.2](https://github.com/customerio/customerio-ios/releases/tag/2.14.2) with support for Firebase 11. I'll go ahead and close this issue, but feel free to reach out if you encounter any problems while upgrading.

**Comment by ThHareau** [comment]
Hi @ami-aman, I might be wrong, but it is not yet incorporated in the flutter SDK, so we cannot use it until the next release of the flutter SDK. Is there another way to use the latest version of firebase when using flutter?

**Comment by ami-aman** [comment]
Hey @ThHareau, 

We’ve added support for the latest Firebase dependencies with version `2.14.2` of the iOS SDK. To make use of this update, follow these steps:

1. Run `flutter pub get` to fetch all the dependencies listed in your `pubspec.yaml`, if they haven’t been downloaded already.
2. From your root directory, run `pod install --repo-update --project-directory=ios` to update your iOS dependencies.

This will fetch the latest version of the iOS SDK, [v2.14.2](https://github.com/customerio/customerio-ios/releases/tag/2.14.2).
You may verify the version from `Podfile.lock` file.
 
Let us know if you encounter any further issues!
