### ISSUE TITLE
iOS device is not attached to user (unable to send push)

### ISSUE THREAD

**Issue by Rokasurba** [customerio/customerio-flutter#20]
Hello all, 

first of all I want to thank developers for this package. It really made the life easier when integrating push notifications in our app using customer.io. Although we seem to have a problem.  iOS users devices are not attached to customer.io user which means we can't send push notf. etc. 

<img width="787" alt="image" src="https://user-images.githubusercontent.com/12084132/217216344-ad1db9f5-12dc-4eab-b7ab-3c508261dba6.png">

In android everything works fine. In iOS user is successfully identified after calling CustomerIo.identify (we can event change the user name by passing req. attributes) but nothing changes in Customer.io admin panel. 

I have reached the dead end and it is unknown if it's problem from code side or configuration. 

I'm using apples APN services (configuration is done in customer io using [this guide](https://customer.io/docs/push-developer-guide/#apns-setup).

Also I've added few swift snippets to present notification to user if he want to receive notifications. 

<img width="757" alt="image" src="https://user-images.githubusercontent.com/12084132/217217543-831e1555-83fa-4319-9563-0dcb4159b703.png">

Flutter doctor:

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale en-LT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
[✓] VS Code (version 1.75.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

Any help will be appreciated. Thanks in advance!

**Comment by Shahroz16** [comment]
Hey @Rokasurba, thank you for reaching out. We have currently not tested this package with APNs, as you will find in [flutter docs](https://customer.io/docs/sdk/flutter/push/), FCM is the only option. But it's on our roadmap, can't commit to the timeline. 

Now to solve this problem, if you are able to generate APNs tokens yourself, in the next couple of days, we will be exposing methods where you can add those tokens by calling those methods. This could be a quick fix to your problem. 

A little later, we will be officially supporting APNs built and you won't have provide the tokens, etc. 

Hope this gives a little clarity.

**Comment by Rokasurba** [comment]
Thanks for quick reply! Yes, now everything makes sense. Documentation got me a bit confused. Will wait for new features and thanks again.

**Comment by Rokasurba** [comment]
Hi once again,

I have switched to using FCM service in iOS but without any success. Push permissions are enabled for the app and all swift code is added as in provided example from [here](https://customer.io/docs/sdk/flutter/push/). iOS device still doesn't appear in customer.io devices. 

Few moments. I've extracted firebase push token using `await FirebaseMessaging.instance.getToken();` and with that token I can send push'es successfully from customer.io push test page. So push notifications works but are not registered. 

One more thing I have noticed is an error in console. Maybe it's culprit?

![image](https://user-images.githubusercontent.com/12084132/217820202-bb113587-4a0a-4578-a9fb-a70fcb4c0298.png)

Let me know if you need more info and I hope we will find the root cause of the problem. :)

**Comment by Shahroz16** [comment]
Hey @Rokasurba, thank you for writing in. Couple of points here, 

> iOS device still doesn't appear in customer.io devices.
Can you please add more detailed logs so we know what might be going wrong? After the identification, the device should automatically get added. Are you asking for notification permission? 

>  I've extracted firebase push token using await FirebaseMessaging.instance.getToken(); and with that token, I can send pushes successfully from customer.io push test page. So push notifications work but are not registered.

For this, we are exposing a method where you can send in the device token, and it will get registered. The PR is attached to this link, hopefully, that method will be exposed by tomorrow.

> The error you showed in logs

Thats expected because when you send a `test` push it doesn't have a `delivery id`. But in real campaigns/broadcast, you won't see this error.

**Comment by Rokasurba** [comment]
Hi @Shahroz16, 

Is flutter debug logs when starting app and identifying user is enough? [Link](https://pastebin.com/eRFnhrCF)
Yes, I'm asking for permission and iOS prompt is displayed. 

> Can you please add more detailed logs so we know what might be going wrong? After the identification, the device should automatically get added. Are you asking for notification permission?

Thanks for PR link. Looking forward to it. :)

**Comment by Shahroz16** [comment]
Thank you for providing logs,

I see there is an error from firebase `APNS device token not set before retrieving FCM Token for Sender ID '167700964239'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.`


To set the APNS device token and retrieve the FCM token, the following steps can be followed:


- Registering for push notifications: On the iOS device, the user needs to grant permission for the app to receive push notifications. This can be done by calling the registerForRemoteNotifications method of the UIApplication class.

- Retrieving the APNS device token: Once the user grants permission, the device token is provided to the app by the system. The app can retrieve the token by implementing the didRegisterForRemoteNotificationsWithDeviceToken method of the UNUserNotificationCenterDelegate protocol. The device token is passed as an argument to this method.

- Setting the APNS device token: After retrieving the device token, the app needs to set it in the FCM instance. This can be done using the Messaging.messaging().apnsToken property.

- Retrieving the FCM token: The final step is to retrieve the FCM token for the given sender ID. This can be done by calling the InstanceID.instanceID().token(withAuthorizedEntity:gcmSenderID:options:handler:) method of the InstanceID class. The FCM token is returned as a result of the completion handler.

After these steps, the app will have the FCM token and will be able to receive push notifications. 
```

**Comment by JakubPatrik** [comment]
> Hey @Rokasurba, thank you for writing in. Couple of points here,
> 
> > iOS device still doesn't appear in customer.io devices.
> > Can you please add more detailed logs so we know what might be going wrong? After the identification, the device should automatically get added. Are you asking for notification permission?
> 
> > I've extracted firebase push token using await FirebaseMessaging.instance.getToken(); and with that token, I can send pushes successfully from customer.io push test page. So push notifications work but are not registered.
> 
> For this, we are exposing a method where you can send in the device token, and it will get registered. The PR is attached to this link, hopefully, that method will be exposed by tomorrow.

Hi, thanks for the explainer, however I still do not get why the device is automatically registered on Android and not on iOS. Looking at the PR, I see that the method `registerDeviceToken` will be added for both platforms. How come is the Android device registered automatically?

**Comment by Shahroz16** [comment]
Hey @JakubPatrik, iOS should automatically register as well. As mentioned in the [docs](https://customer.io/docs/sdk/flutter/push/#add-push-notification-capabilities-in-xcode)


```
class AppDelegate: FlutterAppDelegate {
 func application(
     _ application: UIApplication,
     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
 ) -> Bool {

     GeneratedPluginRegistrant.register(with: self)

     // Configure Firebase
     FirebaseApp.configure()

     // in case, you haven't asked for permissions  
     let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound] // Options: .alert, .badge, .sound
     UNUserNotificationCenter.current().requestAuthorization(options: authOptions, completionHandler: {

         (granted, error) in

         if granted {
             // Register after we get the permissions.
             UNUserNotificationCenter.current().delegate = self
         }
     })        

     // Set FCM messaging delegate
     Messaging.messaging().delegate = self

     // You should register for remote push when the app starts.
     UIApplication.shared.registerForRemoteNotifications()

     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
   }


 func application(application: UIApplication,
                  didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
     Messaging.messaging().setAPNSToken(deviceToken, type: .unknown);
 }

 override func userNotificationCenter(
     _ center: UNUserNotificationCenter,
     didReceive response: UNNotificationResponse,
     withCompletionHandler completionHandler: @escaping () -> Void
 ) {
     let handled = MessagingPush.shared.userNotificationCenter(center, didReceive: response,
                                                               withCompletionHandler: completionHandler)

     // If the Customer.io SDK does not handle the push, it's up to you to handle it and call the
     // completion handler. If the SDK did handle it, it called the completion handler for you.
     if !handled {
         completionHandler()
     }
 }

 }

 extension AppDelegate: MessagingDelegate {
   func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
     MessagingPush.shared.messaging(messaging, didReceiveRegistrationToken: fcmToken)
   }
 }
```


```
     MessagingPush.shared.messaging(messaging, didReceiveRegistrationToken: fcmToken)
```

This line of code should automatically set Token. 

But either this code is not being executed or this is a lifecycle problem, by lifecycle problem I mean, This code is being executed before, and our SDK is being initialized. 

If it's a lifecycle issue, can you try one thing for me? In this method,


```
func application(
     _ application: UIApplication,
     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
 ) -> Bool {
 
  // Important to call this code before calling `registerForRemoteNotifications`. 
     CustomerIO.initialize(siteId: "YOUR SITE ID", apiKey: "YOUR API KEY", region: Region.US, configure: nil)

// and then the rest of the code
 }
```

Thanks looking forward to your response.

**Comment by Rokasurba** [comment]
@Shahroz16  That did the trick! I removed dart `CustomerIO.initialize` method and then added `CustomerIO.initialize` just before `UIApplication.shared.registerForRemoteNotifications()`. After user log in I'm calling  `CustomerIO.identify` from dart and iOS device appeared in user console. FCM token visible and push notifications are working.  

<img width="810" alt="image" src="https://user-images.githubusercontent.com/12084132/218338610-53ffc22a-e95a-4c8d-8569-1cacc6a8a169.png">

One more thing. I had to remove `FirebaseApp.configure()` because it kept throwing error that app is already configured (I'm using firebase for remote configs in my flutter app).

**Comment by Shahroz16** [comment]
Awesome, I'll suggest keeping it on both sides. `dart` and `iOS`. Because since it's a lifecycle issue, maybe the `swift` one doesn't get called. 

And regarding the `FirebaseApp.configure()`, officially we only recommend not having `FCM` as your own dependency, and only relying on FCM dependency from our SDK. 

But if removing this code, works for you, then it would be nice learning on our end as well. Did you try sending push notifications, are they sending through alright?

**Comment by Rokasurba** [comment]
Yes, I have sent few test push notifications and all of them were successful. Yet to try campaign push notifcations.

**Comment by Shahroz16** [comment]
Awesome, thanks for confirming, will be closing this issue for now. Feel free to open/reopen if you bump into any issues.
