### ISSUE TITLE
CustomerIO/MessagingPushFCM is broken

### ISSUE THREAD

**Issue by damienissa** [customerio/customerio-flutter#22]
Hello. I'm receiving an issue when trying to install pods
<img width="821" alt="image" src="https://user-images.githubusercontent.com/17296142/218408989-a50872d5-5bd8-4fd0-825e-5ab55bd7a504.png">

### customer_io: ^1.0.0-alpha.7

**Comment by Shahroz16** [comment]
Hey @damienissa can you try, 

`pod install --repo-update` 

And if that doesn't work, just delete the podLock file and try pod install again.

**Comment by damienissa** [comment]
@Shahroz16  Thank you for the quick response. 
But it was precisely the log of `pod install --repo-update`
I think it can be project-specific, but then I create a new empty project and try to add customer io and receive the same issue.

**Comment by Shahroz16** [comment]
@damienissa I think you are correct, I believe you are following this [link](https://www.customer.io/docs/sdk/flutter/push/#swift-push)

Can you please try, 
```
'CustomerIO/MessagingPushFCM', '~> 2.1.0-beta.1'
```

I'll update the docs as well.

**Comment by damienissa** [comment]
@Shahroz16 Now It works well. 
Also, would be great to receive the ability to set the device FCM token from Flutter.

**Comment by Shahroz16** [comment]
@damienissa so glad to hear that, and regarding your next question, you are in luck 😄 

The [PR](https://github.com/customerio/customerio-flutter/pull/17) is out, I expect it to be merged by today.
