### ISSUE TITLE
Support web

### ISSUE THREAD

**Issue by Jethro87** [customerio/customerio-flutter#29]
Bringing your (already existing) JavaScript SDK into the Flutter SDK would be a great addition, as I'm planning to release web in the near future. Thanks.

**Comment by StephMoreno** [comment]
Hi @Jethro87, 

Me again from the Product team:) 

Taking a look at your note here and just wanted to get some more context on your use case so I can properly document this internally on my end. 

Couple of questions for you, if you don't mind:

- Are you able to use our Web SDK (JavaScript) on it's own?
- Can you provide details of what brining our Web SDK into the Flutter SDK will provide to you? 

Any other info you want to provide will be helpful as we make note of your request. 

Thanks!

Stephanie
