### ISSUE TITLE
onBackgroundMessageReceived / onMessageReceived examples

### ISSUE THREAD

**Issue by FDuhen** [customerio/customerio-flutter#45]
Hey guys,

Could you please update your sample project with an example of the implementation of the methods onBackgroundMessageReceived / onMessageReceived deployed in release 1.1.0 ? 

I may be doing something wrong, because when implementing those methods, CustomerIO displays the notification multiple times.  

My implementation is the following : 
main.dart
```
  //Customer IO
  await CustomerIO.initialize(
    config: CustomerIOConfig(
      siteId: Environment.instance.customerIoId,
      apiKey: Environment.instance.customerIoKey,
      region: Region.eu,
    ),
  );

  //Messaging
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
```

Message Handler method :  
```
@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  await CustomerIO.messagingPush()
      .onBackgroundMessageReceived(message.toMap())
      .then((handled) {
    if (!handled) {
      showLocalNotif(message);
    }

    return handled;
  });

  await CustomerIO.messagingPush()
      .onMessageReceived(message.toMap())
      .then((handled) {
    if (!handled) {
      showLocalNotif(message);
    }

    return handled;
  });
}
```  

AndroidManifest.xml
```
...
        <service
            android:name="io.customer.messagingpush.CustomerIOFirebaseMessagingService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
...
```

With the code above, on an Android 10, and in Release mode : 
- In Background/Foreground => I receive the notification 3 times  

If I comment the AndroidManifest.xml implementation :  
- In Foreground => I don't receive any notification
- In Background => I receive the notification two times   

If I comment the `onBackgroundMessageReceived` method and the AndroidManifest impl : 
- In Foreground => I don't receive any notification  
- In Background => I receive the notification once.  

My local notification is never displayed.   
Didn't try it on iOS.  

It's probably something wrong or misunderstood on my side.

**Comment by mrehan27** [comment]
Hey @FDuhen. Thank you for reaching out and sharing the details. Apologies, we are working on the docs and moving sample apps into SDKs so better explanation of the feature will be available soon.

From looking at your code and to answer your queries, I can summarize as follows:

- The release doesn't change anything for iOS apps, they should work fine with/without implementing these methods. If you encounter any issue for iOS apps, please let us know so we can take a look into it
- To use this method, you must not register `CustomerIOFirebaseMessagingService` in your `AndroidManifest`, if you do, you will receive multiple notifications on your app

Your code looks mostly fine for the listener. But you'll need to move `onMessageReceived` to your main UI class as it is needed for foreground notifications only.

For sample project, you can checkout [this branch](https://github.com/customerio/amiapp-flutter/tree/feat/flutterfire) or [view the difference here](https://github.com/customerio/amiapp-flutter/compare/feat/flutterfire?expand=1). We haven't planned to merge this in `main` right now, but the branch is updated and should help you understand the changes better.

If you have more questions, please let us know so we can assist you better.

**Comment by FDuhen** [comment]
It all makes sense, I don't know why I implemented the `onMessageReceived` in the background handler... thanks a lot !  
I'll test a bit more but so far so good with your explanations 👍
