### ISSUE TITLE
email ID is not capturing for some users

### ISSUE THREAD

**Issue by chenna8464** [customerio/customerio-flutter#46]
email ID is not capturing for some users, I am using  **segment** as the source, 
and also it is creating **anonymous** users with some ID but I am not passing any **AnonymousId** to the segment

let's say I have an event name called APPLICATION OPENED  and I am passing the user ID as Email when the user logs in else passing null  (data from Shared preferences)

<img width="504" alt="Screenshot 2023-05-08 at 3 11 58 PM" src="https://user-images.githubusercontent.com/89239479/236791597-f1339165-dcba-4f40-b83b-daa2c18fb8c1.png">

I am passing just `user email ` as the identifier
<img width="393" alt="Screenshot 2023-05-08 at 4 03 05 PM" src="https://user-images.githubusercontent.com/89239479/236802282-d2034c29-e1f3-4d51-877c-ed1dd30fee55.png">

<img width="483" alt="Screenshot 2023-05-08 at 4 05 23 PM" src="https://user-images.githubusercontent.com/89239479/236802742-07e47c59-0398-4e2d-9949-4127c405e908.png">

**Comment by chenna8464** [comment]
especially this is happening when the `APPLICATION OPENED`  event calling, 
and i am passing the  user identify data to the segment and also passing `email` in the traits

<img width="537" alt="Screenshot 2023-05-08 at 4 08 30 PM" src="https://user-images.githubusercontent.com/89239479/236803403-fcfe2fb6-395a-4db9-b1ba-f27780f8359c.png">
<img width="525" alt="Screenshot 2023-05-08 at 4 09 42 PM" src="https://user-images.githubusercontent.com/89239479/236803599-6952bff3-94de-42fe-a551-5a631137b785.png">

**Comment by Shahroz16** [comment]
Hey, @chenna8464 thank you for writing in, Segment - CustomerIO integration requires you to fill out data in a particular format and make sure needed parameters are provided. 

Please check out this [doc](https://customer.io/docs/segment-destination/) as it would help you in providing all the needed params, also [anonymous profile information ](https://customer.io/docs/segment-destination/#anonymous-events)can be found in it.

**Comment by Shahroz16** [comment]
Closing this, feel free to re-open if you encounter any challenges.
