### ISSUE TITLE
Can't build app on Android 

### ISSUE THREAD

**Issue by ifeanyi-earnipay** [customerio/customerio-flutter#49]
I keep getting this error:

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkProductionDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:productionDebugRuntimeClasspath'.
   > Failed to transform moshi-1.14.0.jar (com.squareup.moshi:moshi:1.14.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for JetifyTransform: /Users/ifeanyi/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.14.0/df173a3bfa0bd9e0cd2a8fc14b24fc336dca0de0/moshi-1.14.0.jar.
         > Failed to transform '/Users/ifeanyi/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.14.0/df173a3bfa0bd9e0cd2a8fc14b24fc336dca0de0/moshi-1.14.0.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 60. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
`

Flutter doctor: 

`Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel stable, 3.7.0, on macOS 13.3.1 22E261 darwin-arm64, locale en-NG)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
`

If i remove the customer io dependency from pubspec.yaml, the app runs fine.

**Comment by Shahroz16** [comment]
Hey @ifeanyi-earnipay,

Seems like you are using an older version of Gradle, Upgrading your gradle version to at least 7.2.X using [Android Gradle plugin Upgrade Assistant in Android Studio](https://developer.android.com/studio/build/agp-upgrade-assistant) should resolve this.

**Comment by ifeanyi-earnipay** [comment]
This worked. Thanks
