### ISSUE TITLE
In-app messages not working on Android release

### ISSUE THREAD

**Issue by msalman2890** [customerio/customerio-flutter#63]
In-app messages are working fine in debug mode but when I create a release build then unable to receive any in-app message.

Please resolve this issue for Android.

Suggestion: There should be some proper message for the error event **EventType.errorWithMessage** which should indicate the exact issue to the user. At the moment, there is nothing to indicate the user.

**Comment by levibostian** [comment]
Thanks for reporting this issue to us. Sorry you're experiencing this issue. 

When you say in-app messages are not working fine in release builds, are you saying that messages are not showing up? 

What steps are you taking to reproduce this issue? 

What version of the Flutter SDK are you using? 

Is the build configuration for your release builds unique compared to debug builds? 

Any details you could provide would be very helpful to figure out how to help.

**Comment by msalman2890** [comment]
> Thanks for reporting this issue to us. Sorry you're experiencing this issue. 
> 
> When you say in-app messages are not working fine in release builds, are you saying that messages are not showing up? 
> 
> What steps are you taking to reproduce this issue? 
> 
> What version of the Flutter SDK are you using? 
> 
> Is the build configuration for your release builds unique compared to debug builds? 
> 
> Any details you could provide would be very helpful to figure out how to help. 


- Yes, not showing up on the Android phone. (I tried on different versions of Android OS like 9, 10 & 12) 

- Not specific steps to reproduce. It's reproducing all time because in-app messages are not showing up for a single time.

- Flutter SDK version is 3.3.10

- Configurations are same as debug.

- I tried all things from my end but no luck.

**Comment by levibostian** [comment]
We have been able to reproduce this issue and have fixed the issue in the native Android SDK. I'll update this ticket once the Flutter SDK has been updated with this fix, too.

**Comment by msalman2890** [comment]
Thanks for the update, Levi.

Can you deploy this patch separately from the Flutter SDK update because then It will give the incompatibility issue with the project's Flutter version? I would be very grateful. Otherwise, I would have to take care of other plugins as well after the flutter upgrade which can cause the functionality to break.

Thanks in advance.

**Comment by levibostian** [comment]
If the Customer.io Flutter SDK was to release a new production version, what incompatibility issues would you experience? 

I apologize if [my last message](https://github.com/customerio/customerio-flutter/issues/63#issuecomment-1645620361) caused some miscommunication. I mean to say that we are preparing a new release of the Customer.io Flutter plugin, not making any updates to Flutter and it's version.

**Comment by msalman2890** [comment]
Oh okay, got it.

Thanks

**Comment by msalman2890** [comment]
@levibostian Btw have you verified it on iOS as well because It seems like non-functional on iOS release as well.

**Comment by mrehan27** [comment]
@msalman2890 I'm Rehan, stepping in for Levi. The fix for Android has been released. Please update to the [latest SDK](https://github.com/customerio/customerio-flutter/releases)(`1.2.4`), and it should resolve the problem for you.

Regarding iOS, we have made attempts to reproduce the issue but have been unsuccessful. Can you please reverify it with the updated SDK and let us know if the problem persists.

Closing this issue as the problem has been fixed for Android. However, please remember that even though this issue is closed, you are free to reopen it or open a new one if you encounter any other problems or need further assistance. Thank you!
