### ISSUE TITLE
Opening a notification on Android restarts the app after switching to Customer.io Flutter Plugin 

### ISSUE THREAD

**Issue by Andrey-K-Calven** [customerio/customerio-flutter#67]
After adding Customer.io Flutter Plugin to the app opening a notification results in an app restart.

I was following the steps here https://customer.io/docs/sdk/flutter/getting-started/ and everything is working: notifications are received and open the app, even deep links navigate correctly. On iOS, when opening a notification,  the app is correctly foregrounded if in background and navigated if already i foreground. However, **on Android the app is instead restarted (main() function is called again) when it's either in the background or the foreground**.

Prior to adding Customer.io Flutter Plugin opening a notification on Android did not cause a restart.

This happens only with notifications (with or w/o deep link), manually foregrounding the app or opening a deeplink from text does not cause restart.

The `android:launchMode` is `singleTask`

Using customer_io: 1.2.3, firebase_messaging: 14.6.5, flutter 3.10.5

**Comment by mrehan27** [comment]
Thank you for sharing and reaching out to us. We are aware of this issue and the challenges surrounding it. I have added a vote on your behalf to our internal ticket. This will help us prioritize the issue and consider it for future updates.

We appreciate your valuable feedback, and we'll keep you posted on any developments.

**Comment by sebr** [comment]
@mrehan27 are you able to provide any more substantive timing or prioritisation on when this will be looked at? We love customerio... and it is disappointing that this is causing major product experience issues for us.

**Comment by mrehan27** [comment]
@sebr Thank you so much for showing your support. We truly appreciate your love and feedback, and want you to know that your input is invaluable to us.

I understand that certain limitations might impact your experience, and we sincerely apologize for any inconvenience caused. We are constantly striving to enhance our SDK and make it even more user-friendly.

Regarding the feature under discussion, I can't provide specific details on timing or priority at the moment as we haven't yet finalized its priority on our roadmap, unfortunately. However, it is already being discussed by our team. I have added a vote on your behalf too, as this will help us prioritize the feature, and we'll keep sharing updates to this ticket.

Once again, thank you for your support and understanding. If you have any more suggestions or questions, please don't hesitate to reach out to us.

**Comment by mingjunsiek** [comment]
@mrehan27 I've highlighted this [issue](https://github.com/customerio/customerio-flutter/issues/31#issuecomment-1471122087) since 16 March 2023 but its still not fixed yet? This is a bad user experience if each push notification causes the app to restart for android. Is there any alternative workaround that works with the latest version of the package?

**Comment by lj-cio** [comment]
Hi there!  I'm the PM for the mobile team at Customer.io and have been working with the team to prioritize the requests and discussions on this thread and from the earlier issue linked @mingjunsiek.  Although I don't yet have a timeline, I'm happy to share that we've completed the research phase and are discussing next steps.  We'll update as soon as we have one to share.

**Comment by mrehan27** [comment]
Thank you for your patience! I'm happy to share that the changes have been released in version [1.3.1](https://github.com/customerio/customerio-flutter/releases/tag/1.3.1). You can read more details in [our docs](https://www.customer.io/docs/sdk/flutter/push-notifications/deep-links/#push-click-behavior). Please update the package to enjoy latest updates and share your feedback with us if you encounter any issues.
