### ISSUE TITLE
CustomerIO.Builder::build() must be called before obtaining CustomerIO instance, null, null

### ISSUE THREAD

**Issue by agordeev** [customerio/customerio-flutter#68]
I'm getting this crash:

```
I/flutter ( 8449): PlatformException(track, CustomerIO.Builder::build() must be called before obtaining CustomerIO instance, null, null)
I/flutter ( 8449):
I/flutter ( 8449): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:653
I/flutter ( 8449): #1      MethodChannel._invokeMethod
platform_channel.dart:315
I/flutter ( 8449): <asynchronous suspension>
```

when trying to

```
      CustomerIO.track(
        name: 'view-mobile-app',
        attributes: {
          'page': _Tab.home.name,
        },
      );
```

 with **an uninitialized CustomerIO**.

Happens with 1.2.4 only on Android.

**Comment by mrehan27** [comment]
Thanks for sharing the details. The SDK does require to be initialized before calling any other methods. To resolve this, please ensure you initialize the SDK correctly before tracking screen or using any other methods, and you should no longer see the error. If you encounter any difficulties, please share your use case with us for further assistance.

**Comment by agordeev** [comment]
@mrehan27 thanks. Using CustomerIO is optional in my app, so it doesn't have to be initialized. It would be great if SDK could handle this case on its own, like FirebaseAnalytics does.

**Comment by mrehan27** [comment]
Thank you for sharing your use case with us. We appreciate your valuable feedback.

At the moment, the requested feature is not on our roadmap. We currently recommend avoiding calls to the SDK if tracking is not required. However, I've created an internal tracking and added a vote on your behalf so we can discuss and prioritize it internally. We'll keep you updated if there's any progress.

If you have any more ideas or suggestions, please don't hesitate to share them with us. Thanks again for sharing.

**Comment by lj-cio** [comment]
Hi @agordeev, 

I'm a PM at Customer.io and the team forwarded your response as a use case that we could support in the future.  To help understand the flow, can you share more information about your app and how you're using Customer.io?  For the optional case, when (or who) would be able to enable the integration?  

You can also reply to product@customer.io if you'd like to share more detail or jump on a call to discuss your use case in more detail.  I'm closing this thread for now, but feel free to reopen if you'd like to discuss this further here.

Cheers,
LJ
