### ISSUE TITLE
Flutter - Swift Compiler Error after update to 1.2.4

### ISSUE THREAD

**Issue by marceloalvestrela** [customerio/customerio-flutter#70]
Hello,
   I'm facing a problem on `cusomter_io 1.2.4` flutter version. After update to this version it's getting the following error on compile:

```
Swift Compiler Error (Xcode): No such module 'CioInternalCommon'
/Users/marceloalves/.pub-cache/hosted/pub.dev/customer_io-1.2.4/ios/Classes/SwiftCustomerIoPlugin.swift:3:7

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
```

Can anyone help me on that ?

**Comment by levibostian** [comment]
Sorry that you encountered this error, @marceloalvestrela. 

[Try to run the commands listed in this comment](https://github.com/customerio/customerio-flutter/issues/58#issuecomment-1590532938) and see if your error goes away. 

Please, comment back with other errors you encounter while trying these commands. Thanks!

**Comment by marceloalvestrela** [comment]
Still with same problem ! 
- Clean all flutter files
- Pub get all dependencieds
- Pod update 

```Failed to build iOS app
Swift Compiler Error (Xcode): No such module 'CioInternalCommon'
/Users/marceloalves/.pub-cache/hosted/pub.dev/customer_io-1.2.4/ios/Classes/SwiftCustomerIoPlugin.swift:3:7

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.```

**Comment by marceloalvestrela** [comment]
PodFile and Podfile.lock 

[Podfile.lock.txt](https://github.com/customerio/customerio-flutter/files/12346881/Podfile.lock.txt)
[Podfile.txt](https://github.com/customerio/customerio-flutter/files/12346882/Podfile.txt)

**Comment by marceloalvestrela** [comment]
Any news?

**Comment by levibostian** [comment]
Thanks for sending those files. I think I see the issue. 

You followed our Flutter SDK instructions correctly. When you update the Customer.io Flutter SDK, you also need to update the native iOS SDK, too. From looking at the `Podfile`, I believe that is the issue - the native iOS SDK needs updated to latest. I also see the `pod` line of code in the wrong place. 

See these screenshots for what to change. 

![CleanShot 2023-08-16 at 08 40 30@2x](https://github.com/customerio/customerio-flutter/assets/2041082/16762f50-e02d-41bd-8634-33b9450d31b2)
![CleanShot 2023-08-16 at 08 41 38@2x](https://github.com/customerio/customerio-flutter/assets/2041082/c4ef11de-ef6c-4aee-9254-1dacb808ff6d)

Then, run `pod update --repo-update --project-directory=ios` from the root directory of your Flutter project. You should see messages printed to you saying that the update was successful. 

After the Customer.io iOS SDK is updated to the newer version, the error message you are receiving should be gone.

**Comment by marceloalvestrela** [comment]
Resolved. Thanks!

**Comment by levibostian** [comment]
Thanks for asking this question. 

We are making improvements to our docs to better explain this. Sorry for the issue that you had.
