### ISSUE TITLE
Is there a way to automate push notifications from the backend?

### ISSUE THREAD

**Issue by ifeanyi-earnipay** [customerio/customerio-flutter#72]
Previously while using firebase messaging, our backend developers were able to automate push notifications. Since we plan to migrate to customer io fully, is it possible to automate push notifications from the backend to all mobile users without having to manually create a broadcast on the customer io website?

**Comment by Shahroz16** [comment]
Hey @ifeanyi-earnipay, thank you for reaching out. Please feel free to ask this question or any other you might regarding automation [win@customer.io](mailto:win@customer.io).

**Comment by lj-cio** [comment]
@ifeanyi-earnipay, the transactional API is a good replacement for the Firebase approach you described.  Learn more about sending transactional push notifications in our [documentation](https://customer.io/docs/journeys/transactional-api/#transactional-push-notifications) and [API spec](https://customer.io/docs/api/app/#operation/sendPush).
