### ISSUE TITLE
Request: Prompt users for to opt-into notifications

### ISSUE THREAD

**Issue by emirua** [customerio/customerio-flutter#86]
Currently in Android 13 the notification permissions are not allowed by default. Also, iOS requires permission to show remote notifications. Is it possible that the sdk could have a method to check if the permissions have been allowed/rejected/not asked and prompt the user to allow the notifications if needed?

**Comment by mrehan27** [comment]
Thank you for sharing. I've created an internal ticket to track this request. Once it gets prioritized, we'll work on adding this feature and will keep you updated on the progress. Closing this ticket as we've now got it covered with an internal tracking ticket. Your feedback is greatly appreciated.
