### ISSUE TITLE
What to pick as a token when manually adding device to profile?

### ISSUE THREAD

**Issue by antonengelhardt** [customerio/customerio-flutter#96]
Hello,
i am trying to connect a device to a user with Flutter. What do i pick as a token for the registration process? [Your docs](https://customer.io/docs/sdk/flutter/identify/#add-device) suggest that it is possible to add devices manually, but i only see `APNs 400 BadDeviceToken: Device token is invalid or doesn't work with this platform. Register a corrected token.` when i test the implementation. I tried it with user ids, random numbers. 

On a side note: the manual registration is required because for some reason, the device is not automatically added...

Thanks !

**Comment by Shahroz16** [comment]
Hey @antonengelhardt, thank you for reaching out. I am not sure I follow the question, so can you give a bit more detail? 

You can add the token manually by using `CustomerIO.registerDeviceToken(token)`. The token needs to be a valid FCM token, it's going to be different for Android and iOS. 

I see you are using `APN` but I am not sure, how you are creating the token and trying to register it manually.

**Comment by antonengelhardt** [comment]
@Shahroz16 We need to deliver Push notifications to iOS and Android, so we are looking for the easiest way to achieve this.

Now i am manually adding the devices to the profile and the devices are shown there. But i am unsure where do get the FCM token from? How do i get it so that i can call registerDeviceToken()? 

Should i use FCM for iOS and Android or APN for iOS and FCM for Android? How do i get the token if i do each platform separately?

**Comment by Shahroz16** [comment]
@antonengelhardt, the easiest way to set push notifications would be to follow [docs](https://customer.io/docs/sdk/flutter/push-notifications/push/) and let the SDKs add the token automatically for you. 

If you still want to add it manually, you can use [Flutter Fire FCM messaging](https://firebase.flutter.dev/docs/messaging/usage) to get the token and provide it to the CustomerIO

**Comment by antonengelhardt** [comment]
@Shahroz16 I have followed the docs, but my device was never added automatically. So we did it manually.

With Flutterfire, we are able to get the token now. But when i test the token, i get an error for APN:

![Screenshot-Google Chrome-004433](https://github.com/customerio/customerio-flutter/assets/106314688/92e21121-3938-4c2f-87b3-abc1733712a1)

FCM is at least sending the test but it never arrives, although my the value of `push_enabled`is true:

![Screenshot-Google Chrome-004435](https://github.com/customerio/customerio-flutter/assets/106314688/9f3e048e-9029-4746-b31a-b66a776a4a7f)

![Screenshot-Google Chrome-004437](https://github.com/customerio/customerio-flutter/assets/106314688/6188fc60-6f16-4e18-8baa-35ce56c1664e)

**Comment by Shahroz16** [comment]
@antonengelhardt Flutter fire also uses FCM. 

APN won't work out of the box with the SDK. 

Can you please recheck your FCM integration? Did you add the `google-services.json` file in android and similarly the corresponding one for iOS?

**Comment by antonengelhardt** [comment]
@Shahroz16 Thanks for your support.

It was indeed a misconfigured Flutterfire. We have two targets: "Runner" & "Production" and the Test Push notifications where sent to the wrong app. I just got the first message.

**Comment by antonengelhardt** [comment]
@Shahroz16 May i suggest to maybe explain this a little more in the docs? That would have helped me a lot.
